### ISSUE TITLE
Layout-issue when resizing stage

### ISSUE THREAD

**Issue by timoreichen** [AmaronUI/amaronui-layouts#1]
After changing the stage width to be more than 1054 pixels all items are placed on top of the panel. No matter which setting was used. Reproducable by using the demo-app.

**Comment by dukescript** [comment]
I checked the algorithm and found the code responsible for this. It's actually correct behaviour according to the W3C specification. Apparently I found it strange, since I put a comment in the code, that this is correct behaviour in specification.

Still I don't like the behaviour either, and I'll fix it ;-).

**Comment by dukescript** [comment]
fixed in https://github.com/AmaronUI/amaronui-layouts/commit/462538355d9e44e1847cf177b60e2253de5cdac5
